export default {
    PRIMARY_COLOR: '#2aabb8',
    FONT_SIZE_SMALL: 12,
    FONT_SIZE_MEDIUM: 14,
    FONT_SIZE_LARGE: 16,
    HEADER_FONT_SIZE_SMALL: 18,
    HEADER_FONT_SIZE_MEDIUM: 20,
    HEADER_FONT_SIZE_LARGE: 26,
    FONT_WEIGHT_LIGHT: '200',
    FONT_WEIGHT_MEDIUM: '400',
    FONT_WEIGHT_BOLD: '700',
    BACKGROUND_COLOR_LIGHT: '#f0f6f7',
    CONTAINER_PADDING: 20,
    TEXT_INPUT_PADDING: 10,
    TEXT_COLOR: 'white',
    BUTTON_BG_COLOR: '#2d665f',
    BUTTON_TEXT_COLOR: 'white',
    BUTTON_FONT_SIZE: 30
}